  name: Node.js CI

  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

  jobs:
    build:
    
      runs-on: ubutu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhilehns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "bmi-calc-app4080"
            heroku_email: "jroyugi@gmail.com"
            
  

